version: '3'

services:
  db:
    image: postgres:11.4
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - dev.env
    volumes:
      - ./app:/code
    ports:
      - "7665:8000"
    depends_on:
      - db
